micronaut:
  application:
    name: ssi-registry-service
    instance:
      id: ${random.shortuuid}
  server:
    port: 8020
    cors:
      enabled: true
    idle-timeout: 30m
  io:
    watch:
      paths: src/main
      restart: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

jackson:
  deserialization:
    failOnUnknownProperties: false
    acceptEmptyStringAsNullObject: true
    acceptEmptyArrayAsNullObject: true
  mapper:
    acceptCaseInsensitiveEnums: true

mongodb:
  database: registry